key_color = "#e3a659"
separator_color = "#e3a659"

[custom_ascii]
path = "~/.config/macchina/ascii/Hlogo"
color = "#ae82ff"

[palette]
type = "Full"
visible = false

[keys]
host            = "ğŸ’»"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "ğŸ’¿"
terminal        = "Terminal"
shell           = "ğŸš"
packages        = "ğŸ“¦"
uptime          = "Uptime"
memory          = "ğŸ§ "
machine         = "Machine"
local_ip        = "Local IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "âš¡"
cpu             = "CPU"
gpu             = "ğŸ’³"
disk_space      = "Disk Space"
